Added required max size limit argument to the small file option.
Previously, the max size limit was hard coded, now it is a required argument when using the small file option.

diff --git a/diskmv b/diskmv
--- a/diskmv
+++ b/diskmv
@@ -9,6 +9,14 @@
 usage(){
 cat << EOF
 
+usage: diskmv [-t|-f|-k|-l|-c|-s N|-v|-q|-h] directory srcdisk destdisk
+
+EOF
+}
+
+helpmsg(){
+cat << EOF
+
 usage: diskmv [options] directory srcdisk destdisk
 
 directory    Any directory that is contained in the user share file system.
@@ -28,7 +36,7 @@ Options:
 -k	keep source files, do not delete after successful copy
 -l	link, copy symlinks as symlinks, default is to ignore symlinks
 -c	clobber, duplicates on destination will be overwritten
--s      small, only move files smaller than 4096 bytes
+-s N    small, only move files smaller than N kilobytes
 -v	verbose, output more information
 -q	quiet, output less information
 -h	help, print this help message
@@ -43,13 +51,12 @@ keepsrc='false'   # Delete source files by default if copy works
 symlinks='false'  # Default rsync to not copy symlinks as symlinks
 clobber='false'   # Default to skip duplicates
 small='false'     # Default to not limit file size
-maxsize=4k        # Default to 4096 byte max file size for small files
 verbose=1	  # Default to output some but not all info
 
 while :; do
   case "$1" in
     -h|-\?|--help)
-      usage
+      helpmsg
       exit 0
       ;;
     -t|--test) # Specify test mode where no files are moved
@@ -69,6 +76,8 @@ while :; do
       ;;
     -s|--small) # Only move files smaller than 4096 bytes
       small='true'
+      maxsize="$2"
+      shift
       ;;
     -v|--verbose)
       verbose=$((verbose + 1)) # Each -v argument adds 1 to verbosity
@@ -87,6 +96,20 @@ while :; do
   esac
   shift
 done
+
+if [ "$small" == 'true' ]; then
+  if [ -z "$maxsize" ]; then
+    echo "The -s (--small) option requires an integer argument." >&2
+    usage >&2
+    exit 1
+  fi
+  re='^[1-9][0-9]*$'  #Regular expression for only digits not starting with 0
+  if [[ ! "$maxsize" =~ $re ]]; then
+    echo "Invalid argument: '$maxsize' for the -s (--small) option." >&2
+    usage >&2
+    exit 1
+  fi
+fi
 
 if [ -d "$1" ]
 then
@@ -193,7 +216,7 @@ else
 fi
 
 if [ "$small" == 'true' ]; then
-  SIZECLAUSE="-size -$maxsize"
+  SIZECLAUSE="-size -$((maxsize*1024))c"
 else
   SIZECLAUSE=""
 fi
